## Basic Configuration

baseurl = "https://robert.dybvad.net/"
languageCode = "en-US"

author = "Robert Zahl Dybvad"
title = "Robert Zahl Dybvad"


## Site Settings
[params]
author = "Robert Zahl Dybvad"
intro = "Cybersecurity engineer and privacy advocate"
authorimage = "RobertDybvad.jpg"
keysUpdated = "22. Apr 2024"

## Social Accounts
[[params.socialLinks]]
name = "GitHub"
url = "https://github.com/robertzd"

[[params.socialLinks]]
name = "LinkedIn"
url = "https://linkedin.com/in/robertzahldybvad"

[[params.socialLinks]]
name = "Mastodon"
url = "https://infosec.exchange/@robertdybvad"

[[params.socialLinks]]
name = "Signal"
url = "https://signal.me/#eu/88cEsSjE-3Aa-jXCM1IWYyzFCW7dhhPF4aXhv-vwDIgSpcJW_ldKla4Jg8Ymp2u0"

[[params.publicKeys]]
name = "GPG"
url = "/GPG-RobertZahlDybvad-0xC8459FBAD84709D1-Public.asc"

[[params.publicKeys]]
name = "SSH"
url = "/SSH-RobertZahlDybvad-id_rsa.pub"

## Extras
[params.extra]
copyrightText = "Robert Zahl Dybvad [Some Rights Reserved](https://creativecommons.org/licenses/by/4.0/deed.en)."
